import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
    Calendar, Clock, MapPin, Lightbulb, RefreshCw, ChevronDown, ChevronUp, 
    Sparkles, Download, Copy, Check, Printer, Compass, Zap, Coffee, 
    Sliders, Backpack, Landmark
} from 'lucide-react';
import { useItinerary } from '@/hooks/useGemini';
import { ErrorCard } from '@/components/ui/ErrorCard';
import { SkeletonText } from '@/components/ui/Skeleton';
import { cn } from '@/utils/motion';
import { useToast } from '@/context/ToastContext';

const DAY_OPTIONS = [1, 2, 3, 4, 5, 7];

const PACING_OPTIONS = [
    { 
        id: 'Relaxed', 
        label: 'Relaxed', 
        subtitle: 'Unhurried, scenic stops', 
        icon: Coffee 
    },
    { 
        id: 'Balanced', 
        label: 'Balanced', 
        subtitle: 'Optimal sights & leisure', 
        icon: Compass 
    },
    { 
        id: 'High Adventure', 
        label: 'High Adventure', 
        subtitle: 'Sunrise to dusk action', 
        icon: Zap 
    }
];

const STYLE_OPTIONS = [
    { 
        id: 'Backpacker', 
        label: 'Backpacker', 
        subtitle: 'Transit hacks & markets', 
        icon: Backpack 
    },
    { 
        id: 'Boutique Explorer', 
        label: 'Boutique Explorer', 
        subtitle: 'Ateliers & hidden alleys', 
        icon: Landmark 
    },
    { 
        id: 'Luxury Expedition', 
        label: 'Luxury Expedition', 
        subtitle: 'VIP access & fine dining', 
        icon: Sparkles 
    }
];

const PREFERENCE_OPTIONS = [
    'Culture & Arts', 'Local Cuisine', 'Wild Nature', 'Adventure Sports', 
    'Relaxation', 'Historic Sites', 'Nightlife', 'Hidden Gems', 
    'Photography', 'Budget-Friendly'
];

function generateItineraryMarkdown(destinationName, country, days, pacing, travelStyle, selectedPrefs, checkedActivities) {
    let md = `# 🌍 ${destinationName}, ${country} — ${days.length}-Day Expedition Itinerary\n`;
    md += `*Curated AI Travel Blueprint · Generated by Wanderlust AI Concierge*\n\n`;
    md += `### Expedition Parameters\n`;
    md += `- **Duration**: ${days.length} Days\n`;
    md += `- **Pacing**: ${pacing}\n`;
    md += `- **Travel Style**: ${travelStyle}\n`;
    md += `- **Interests**: ${selectedPrefs.length > 0 ? selectedPrefs.join(', ') : 'All-Round Exploration'}\n\n`;
    md += `---\n\n`;

    days.forEach((day, dayIdx) => {
        md += `## 📅 Day ${day.day}: ${day.theme}\n\n`;
        day.activities.forEach((act, actIdx) => {
            const isChecked = checkedActivities[`${dayIdx}-${actIdx}`];
            const checkMark = isChecked ? '[x] (Completed)' : '[ ] (Planned)';
            md += `### ${checkMark} ${act.time} · ${act.period || 'Activity'} — ${act.activity}\n`;
            md += `- 📍 **Location**: ${act.location}\n`;
            if (act.category) md += `- 🏷️ **Category**: ${act.category}\n`;
            if (act.tip) md += `- 💡 **Insider Tip**: ${act.tip}\n`;
            md += `\n`;
        });
        md += `---\n\n`;
    });

    md += `*Created with Wanderlust AI Expedition Planner*\n`;
    return md;
}

export function ItineraryPanel({ destinationName = "Global", country = "World", className }) {
    const isGlobal = destinationName === "Global" || destinationName === "Anywhere";
    const titleContext = isGlobal ? "Curated World Expedition" : destinationName;
    const { days, status, error, generate } = useItinerary(titleContext, country);
    
    // Planner state
    const [numDays, setNumDays] = useState(3);
    const [pacing, setPacing] = useState('Balanced');
    const [travelStyle, setTravelStyle] = useState('Boutique Explorer');
    const [selectedPrefs, setSelectedPrefs] = useState(['Wild Nature', 'Local Cuisine', 'Photography']);
    
    // UI state
    const toast = useToast();
    const [showControls, setShowControls] = useState(true);
    const [expandedDays, setExpandedDays] = useState({ 1: true });
    const [checkedActivities, setCheckedActivities] = useState({});
    const [copied, setCopied] = useState(false);

    function togglePref(pref) {
        setSelectedPrefs((prev) => 
            prev.includes(pref) ? prev.filter((p) => p !== pref) : [...prev, pref]
        );
    }

    function handleGenerate() {
        void generate(numDays, selectedPrefs, pacing, travelStyle);
        // Automatically collapse controls on mobile/desktop to focus on itinerary
        setShowControls(false);
        // Expand first day by default
        setExpandedDays({ 1: true });
    }

    function toggleDay(dayNumber) {
        setExpandedDays((prev) => ({
            ...prev,
            [dayNumber]: !prev[dayNumber]
        }));
    }

    function toggleExpandAll() {
        const anyCollapsed = days.some(d => !expandedDays[d.day]);
        const newState = {};
        days.forEach(d => {
            newState[d.day] = anyCollapsed;
        });
        setExpandedDays(newState);
    }

    function toggleActivityChecked(dayIdx, actIdx) {
        const key = `${dayIdx}-${actIdx}`;
        setCheckedActivities((prev) => ({
            ...prev,
            [key]: !prev[key]
        }));
    }

    function handleDownloadPlan() {
        if (!days || days.length === 0) return;
        const markdown = generateItineraryMarkdown(destinationName, country, days, pacing, travelStyle, selectedPrefs, checkedActivities);
        const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        const safeName = destinationName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
        link.download = `${safeName}-itinerary-${days.length}days.md`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        toast.success('Itinerary Downloaded', `${days.length}-Day markdown plan exported successfully.`);
    }

    async function handleCopyPlan() {
        if (!days || days.length === 0) return;
        const markdown = generateItineraryMarkdown(destinationName, country, days, pacing, travelStyle, selectedPrefs, checkedActivities);
        try {
            await navigator.clipboard.writeText(markdown);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
            toast.copy('Itinerary Copied', `${days.length}-Day ${destinationName} plan copied to clipboard!`);
        } catch {
            const textarea = document.createElement('textarea');
            textarea.value = markdown;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
            toast.copy('Itinerary Copied', `${days.length}-Day ${destinationName} plan copied to clipboard!`);
        }
    }

    function handlePrint() {
        // Expand all days for clean printing
        const allExpanded = {};
        days.forEach(d => { allExpanded[d.day] = true; });
        setExpandedDays(allExpanded);
        setTimeout(() => {
            window.print();
        }, 150);
    }

    // Calculations
    const totalActivities = days.reduce((acc, d) => acc + (d.activities?.length || 0), 0);
    const completedCount = Object.values(checkedActivities).filter(Boolean).length;
    const progressPercent = totalActivities > 0 ? Math.round((completedCount / totalActivities) * 100) : 0;

    return (
        <div 
            className={cn(
                'flex flex-col h-full w-full justify-between rounded-3xl border border-white/10 bg-[#0f0c24]/90 backdrop-blur-2xl shadow-2xl shadow-purple-950/50 overflow-hidden',
                className
            )}
            aria-label="Trip itinerary planner"
        >
            {/* Header */}
            <div className="px-6 md:px-8 py-5 border-b border-white/10 bg-white/[0.02] flex items-center justify-between gap-4">
                <div>
                    <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#FF6B6B] mb-1">
                        <Calendar size={14} />
                        <span>Algorithmic Itinerary Architect</span>
                    </div>
                    <h2 className="text-xl md:text-2xl font-bold tracking-tight text-white">
                        {isGlobal ? "Craft Custom Journey" : `Plan Your ${destinationName} Trip`}
                    </h2>
                    <p className="text-xs md:text-sm text-neutral-400 mt-0.5">
                        Interactive day-by-day scheduling customized to your style
                    </p>
                </div>

                {status === 'success' && (
                    <button
                        type="button"
                        onClick={() => setShowControls(prev => !prev)}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold text-neutral-300 hover:text-white bg-white/5 hover:bg-white/10 border border-white/10 transition-all flex-shrink-0 shadow-sm"
                        title="Toggle parameters panel"
                    >
                        <Sliders size={13} className="text-[#FF6B6B]" />
                        <span className="hidden sm:inline">{showControls ? 'Hide Filters' : 'Adjust Settings'}</span>
                    </button>
                )}
            </div>

            {/* Controls Drawer / Form */}
            <AnimatePresence initial={false}>
                {(showControls || status !== 'success') && (
                    <motion.div 
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.25 }}
                        className="border-b border-white/10 bg-black/20 overflow-hidden"
                    >
                        <div className="p-6 md:p-8 space-y-6">
                            {/* Days selector */}
                            <div>
                                <div className="flex items-center justify-between mb-3">
                                    <label className="text-xs font-bold uppercase tracking-widest text-neutral-300 flex items-center gap-1.5">
                                        <Clock size={13} className="text-[#FF6B6B]" />
                                        Expedition Duration
                                    </label>
                                    <span className="text-xs text-neutral-400 font-medium">
                                        {numDays} {numDays === 1 ? 'Day' : 'Days'} planned
                                    </span>
                                </div>
                                <div className="grid grid-cols-6 gap-2 sm:gap-3 max-w-xl">
                                    {DAY_OPTIONS.map((n) => {
                                        const isActive = numDays === n;
                                        return (
                                            <button 
                                                key={n} 
                                                type="button" 
                                                onClick={() => setNumDays(n)} 
                                                aria-pressed={isActive} 
                                                className={cn(
                                                    'py-3 rounded-2xl text-sm font-bold border transition-all duration-200 flex flex-col items-center justify-center gap-0.5',
                                                    isActive
                                                        ? 'bg-gradient-to-r from-[#FF6B6B] to-[#7c3aed] text-white border-transparent shadow-lg shadow-purple-900/40 scale-[1.02]'
                                                        : 'bg-white/5 border-white/10 text-neutral-300 hover:border-white/30 hover:bg-white/10'
                                                )}
                                            >
                                                <span className="text-base leading-none">{n}</span>
                                                <span className="text-[9px] font-normal uppercase opacity-75">Days</span>
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Pacing selector */}
                            <div>
                                <label className="text-xs font-bold uppercase tracking-widest text-neutral-300 block mb-3">
                                    Travel Pacing
                                </label>
                                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 max-w-2xl">
                                    {PACING_OPTIONS.map((opt) => {
                                        const Icon = opt.icon;
                                        const isActive = pacing === opt.id;
                                        return (
                                            <button
                                                key={opt.id}
                                                type="button"
                                                onClick={() => setPacing(opt.id)}
                                                className={cn(
                                                    'p-3.5 rounded-2xl border text-left transition-all duration-200 flex items-start gap-3',
                                                    isActive
                                                        ? 'bg-purple-950/60 border-[#FF6B6B] shadow-md shadow-[#FF6B6B]/10'
                                                        : 'bg-white/5 border-white/10 hover:border-white/20 hover:bg-white/10 text-neutral-300'
                                                )}
                                            >
                                                <div className={cn(
                                                    'w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0 mt-0.5',
                                                    isActive ? 'bg-[#FF6B6B] text-white shadow-md' : 'bg-white/10 text-neutral-400'
                                                )}>
                                                    <Icon size={16} />
                                                </div>
                                                <div>
                                                    <p className={cn('text-xs font-bold', isActive ? 'text-white' : 'text-neutral-200')}>
                                                        {opt.label}
                                                    </p>
                                                    <p className="text-[11px] text-neutral-400 mt-0.5 leading-tight">
                                                        {opt.subtitle}
                                                    </p>
                                                </div>
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Travel Style selector */}
                            <div>
                                <label className="text-xs font-bold uppercase tracking-widest text-neutral-300 block mb-3">
                                    Travel Style
                                </label>
                                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 max-w-2xl">
                                    {STYLE_OPTIONS.map((opt) => {
                                        const Icon = opt.icon;
                                        const isActive = travelStyle === opt.id;
                                        return (
                                            <button
                                                key={opt.id}
                                                type="button"
                                                onClick={() => setTravelStyle(opt.id)}
                                                className={cn(
                                                    'p-3.5 rounded-2xl border text-left transition-all duration-200 flex items-start gap-3',
                                                    isActive
                                                        ? 'bg-purple-950/60 border-[#FF6B6B] shadow-md shadow-[#FF6B6B]/10'
                                                        : 'bg-white/5 border-white/10 hover:border-white/20 hover:bg-white/10 text-neutral-300'
                                                )}
                                            >
                                                <div className={cn(
                                                    'w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0 mt-0.5',
                                                    isActive ? 'bg-gradient-to-tr from-[#FF6B6B] to-[#7c3aed] text-white shadow-md' : 'bg-white/10 text-neutral-400'
                                                )}>
                                                    <Icon size={16} />
                                                </div>
                                                <div>
                                                    <p className={cn('text-xs font-bold', isActive ? 'text-white' : 'text-neutral-200')}>
                                                        {opt.label}
                                                    </p>
                                                    <p className="text-[11px] text-neutral-400 mt-0.5 leading-tight">
                                                        {opt.subtitle}
                                                    </p>
                                                </div>
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Preferences / Tags */}
                            <div>
                                <label className="text-xs font-bold uppercase tracking-widest text-neutral-300 block mb-3">
                                    Travel Interests ({selectedPrefs.length} selected)
                                </label>
                                <div className="flex flex-wrap gap-2">
                                    {PREFERENCE_OPTIONS.map((pref) => {
                                        const isSelected = selectedPrefs.includes(pref);
                                        return (
                                            <button
                                                key={pref}
                                                type="button"
                                                onClick={() => togglePref(pref)}
                                                className={cn(
                                                    'px-3.5 py-1.5 rounded-full text-xs font-bold transition-all duration-200 border select-none',
                                                    isSelected
                                                        ? 'bg-white text-black border-white shadow-md'
                                                        : 'bg-white/5 border-white/10 text-neutral-300 hover:border-white/30 hover:text-white'
                                                )}
                                            >
                                                {pref}
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Generate Action Button */}
                            <button 
                                type="button"
                                onClick={handleGenerate} 
                                disabled={status === 'loading'}
                                className="w-full py-4 px-8 rounded-full bg-gradient-to-r from-[#FF6B6B] to-[#7c3aed] text-white font-bold text-xs uppercase tracking-widest hover:shadow-xl hover:shadow-purple-900/50 hover:scale-[1.01] active:scale-[0.99] disabled:opacity-50 transition-all flex items-center justify-center gap-3 shadow-lg"
                            >
                                <Sparkles size={16} />
                                {status === 'loading' ? 'Synthesizing Expedition Plan…' : `Generate ${numDays}-Day ${pacing} Plan`}
                            </button>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Empty State when no itinerary generated yet */}
            {status === 'idle' && days.length === 0 && (
                <div className="flex-1 flex flex-col items-center justify-center p-8 text-center space-y-4">
                    <div className="w-16 h-16 rounded-3xl bg-white/5 border border-white/10 flex items-center justify-center text-[#FF6B6B]">
                        <Compass size={32} />
                    </div>
                    <div className="max-w-sm">
                        <h3 className="text-base font-bold text-white mb-1">Tailor Your Ideal Route</h3>
                        <p className="text-xs text-neutral-400">
                            Select your preferred days, pacing, and interests above, then tap Generate to create your interactive day-by-day expedition plan.
                        </p>
                    </div>
                </div>
            )}

            {/* Loading skeleton */}
            {status === 'loading' && (
                <div className="p-6 md:p-8 space-y-4 flex-1" aria-label="Generating itinerary">
                    <div className="h-4 w-48 bg-white/10 rounded animate-pulse mb-6" />
                    {Array.from({ length: numDays }).map((_, i) => (
                        <div key={i} className="rounded-2xl border border-white/10 bg-white/5 p-5 space-y-3 animate-pulse">
                            <div className="flex items-center gap-3">
                                <div className="w-8 h-8 rounded-xl bg-white/20" />
                                <div className="h-5 w-48 bg-white/15 rounded-md" />
                            </div>
                            <SkeletonText lines={3} />
                        </div>
                    ))}
                </div>
            )}

            {/* Error state */}
            {status === 'error' && error && (
                <div className="p-8 flex-1">
                    <ErrorCard title="Couldn't generate itinerary" message={error} onRetry={handleGenerate} />
                </div>
            )}

            {/* Success: Real readable Day-by-Day Plan */}
            <AnimatePresence>
                {status === 'success' && days.length > 0 && (
                    <motion.div 
                        initial={{ opacity: 0 }} 
                        animate={{ opacity: 1 }} 
                        className="p-5 md:p-7 space-y-5 flex-1 overflow-y-auto no-scrollbar"
                    >
                        {/* Control Bar: Actions & Completion Tracker */}
                        <div className="rounded-2xl bg-white/[0.03] border border-white/10 p-4 space-y-3">
                            <div className="flex flex-wrap items-center justify-between gap-3">
                                <div>
                                    <div className="flex items-center gap-2">
                                        <span className="text-xs font-bold uppercase tracking-wider text-[#FF6B6B]">
                                            {days.length}-Day Plan
                                        </span>
                                        <span className="text-neutral-500 text-xs">·</span>
                                        <span className="text-xs text-neutral-300 font-medium">{pacing}</span>
                                        <span className="text-neutral-500 text-xs">·</span>
                                        <span className="text-xs text-purple-300 font-medium">{travelStyle}</span>
                                    </div>
                                    <p className="text-[11px] text-neutral-400 mt-0.5">
                                        {completedCount} of {totalActivities} activities completed ({progressPercent}%)
                                    </p>
                                </div>

                                {/* Plan Action Controls */}
                                <div className="flex flex-wrap items-center gap-2">
                                    {/* Copy Plan Button */}
                                    <button
                                        type="button"
                                        onClick={handleCopyPlan}
                                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-neutral-300 hover:text-white transition-all shadow-sm"
                                        title="Copy formatted markdown itinerary"
                                    >
                                        {copied ? (
                                            <>
                                                <Check size={13} className="text-emerald-400" />
                                                <span className="text-emerald-400">Copied!</span>
                                            </>
                                        ) : (
                                            <>
                                                <Copy size={13} className="text-neutral-400" />
                                                <span>Copy Plan</span>
                                            </>
                                        )}
                                    </button>

                                    {/* Export / Download Plan Button */}
                                    <button
                                        type="button"
                                        onClick={handleDownloadPlan}
                                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-neutral-300 hover:text-white transition-all shadow-sm"
                                        title="Download .md itinerary file"
                                    >
                                        <Download size={13} className="text-[#FF6B6B]" />
                                        <span>Export .MD</span>
                                    </button>

                                    {/* Print Itinerary Button */}
                                    <button
                                        type="button"
                                        onClick={handlePrint}
                                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-neutral-300 hover:text-white transition-all shadow-sm"
                                        title="Open clean print preview"
                                    >
                                        <Printer size={13} className="text-purple-400" />
                                        <span>Print</span>
                                    </button>

                                    {/* Expand/Collapse All */}
                                    <button
                                        type="button"
                                        onClick={toggleExpandAll}
                                        className="px-2.5 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-neutral-400 hover:text-white text-xs transition-colors"
                                        title="Expand or collapse all days"
                                    >
                                        {days.some(d => !expandedDays[d.day]) ? <ChevronDown size={14} /> : <ChevronUp size={14} />}
                                    </button>

                                    {/* Regenerate Button */}
                                    <button
                                        type="button"
                                        onClick={handleGenerate}
                                        className="px-2.5 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-neutral-400 hover:text-white text-xs transition-colors"
                                        title="Regenerate itinerary"
                                    >
                                        <RefreshCw size={14} />
                                    </button>
                                </div>
                            </div>

                            {/* Progress bar */}
                            <div className="w-full h-1.5 rounded-full bg-white/10 overflow-hidden">
                                <motion.div 
                                    className="h-full bg-gradient-to-r from-[#FF6B6B] to-[#7c3aed]"
                                    initial={{ width: 0 }}
                                    animate={{ width: `${progressPercent}%` }}
                                    transition={{ duration: 0.3 }}
                                />
                            </div>
                        </div>

                        {/* Day Cards List */}
                        <div className="space-y-3.5" id="itinerary-printable-content">
                            {days.map((day, dayIndex) => (
                                <ItineraryDayCard 
                                    key={day.day} 
                                    day={day} 
                                    dayIndex={dayIndex}
                                    isExpanded={Boolean(expandedDays[day.day])}
                                    onToggle={() => toggleDay(day.day)}
                                    checkedActivities={checkedActivities}
                                    onToggleActivity={(actIdx) => toggleActivityChecked(dayIndex, actIdx)}
                                />
                            ))}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}

function ItineraryDayCard({ day, dayIndex, isExpanded, onToggle, checkedActivities, onToggleActivity }) {
    const dayActivitiesCount = day.activities?.length || 0;
    const completedCount = day.activities?.filter((_, idx) => checkedActivities[`${dayIndex}-${idx}`]).length || 0;

    return (
        <motion.div 
            initial={{ opacity: 0, y: 12 }} 
            animate={{ opacity: 1, y: 0 }} 
            transition={{ delay: dayIndex * 0.06 }} 
            className="rounded-2xl border border-white/10 bg-white/[0.03] overflow-hidden backdrop-blur-md shadow-lg"
        >
            {/* Header Accordion Button */}
            <button 
                type="button" 
                onClick={onToggle} 
                aria-expanded={isExpanded} 
                className="w-full px-5 py-4 flex items-center justify-between gap-4 text-left hover:bg-white/5 transition-colors group"
            >
                <div className="flex items-center gap-3.5">
                    <span className="w-9 h-9 rounded-xl bg-gradient-to-tr from-[#FF6B6B] to-[#7c3aed] text-white text-xs font-bold flex items-center justify-center flex-shrink-0 shadow-md">
                        {day.day}
                    </span>
                    <div>
                        <div className="flex items-center gap-2">
                            <span className="text-[10px] text-[#FF6B6B] font-bold uppercase tracking-wider">
                                Day {day.day}
                            </span>
                            <span className="text-[10px] text-neutral-400 bg-white/5 px-2 py-0.5 rounded-full border border-white/5">
                                {completedCount}/{dayActivitiesCount} done
                            </span>
                        </div>
                        <p className="font-bold text-white text-sm md:text-base leading-snug group-hover:text-purple-200 transition-colors">
                            {day.theme}
                        </p>
                    </div>
                </div>
                <motion.span 
                    animate={{ rotate: isExpanded ? 180 : 0 }} 
                    transition={{ duration: 0.2 }} 
                    aria-hidden="true" 
                    className="text-neutral-400 group-hover:text-white transition-colors"
                >
                    <ChevronDown size={18} />
                </motion.span>
            </button>

            {/* Activities List */}
            <AnimatePresence initial={false}>
                {isExpanded && (
                    <motion.div 
                        initial={{ height: 0, opacity: 0 }} 
                        animate={{ height: 'auto', opacity: 1 }} 
                        exit={{ height: 0, opacity: 0 }} 
                        transition={{ duration: 0.22 }} 
                        className="overflow-hidden"
                    >
                        <div className="px-5 pb-5 pt-2 space-y-4 border-t border-white/5">
                            {day.activities.map((act, actIdx) => {
                                const isChecked = Boolean(checkedActivities[`${dayIndex}-${actIdx}`]);
                                return (
                                    <div 
                                        key={actIdx} 
                                        className={cn(
                                            'p-3.5 rounded-xl border transition-all duration-200 flex items-start gap-3.5',
                                            isChecked 
                                                ? 'bg-emerald-950/20 border-emerald-500/30 opacity-80' 
                                                : 'bg-white/[0.02] border-white/10 hover:border-white/20'
                                        )}
                                    >
                                        {/* Interactive Checkbox */}
                                        <button
                                            type="button"
                                            onClick={() => onToggleActivity(actIdx)}
                                            className={cn(
                                                'mt-1 w-5 h-5 rounded-md flex items-center justify-center transition-colors flex-shrink-0',
                                                isChecked 
                                                    ? 'bg-emerald-500 text-black shadow-md' 
                                                    : 'border border-white/30 hover:border-[#FF6B6B] text-transparent hover:text-white/40'
                                            )}
                                            aria-label={isChecked ? `Mark as uncompleted` : `Mark as completed`}
                                            title={isChecked ? "Activity completed" : "Check off activity"}
                                        >
                                            <Check size={13} strokeWidth={3} />
                                        </button>

                                        {/* Activity Details */}
                                        <div className="flex-1 min-w-0 space-y-1.5">
                                            {/* Badges row: Time, Period, Category */}
                                            <div className="flex flex-wrap items-center gap-2">
                                                <span className="flex items-center gap-1 text-[11px] text-neutral-300 font-mono font-semibold bg-white/10 px-2 py-0.5 rounded-md">
                                                    <Clock size={11} className="text-[#FF6B6B]" />
                                                    <span>{act.time}</span>
                                                </span>
                                                {act.period && (
                                                    <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-md bg-[#FF6B6B]/20 text-[#FF6B6B]">
                                                        {act.period}
                                                    </span>
                                                )}
                                                {act.category && (
                                                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded-md bg-purple-950/60 border border-purple-500/30 text-purple-200">
                                                        {act.category}
                                                    </span>
                                                )}
                                                {isChecked && (
                                                    <span className="text-[10px] font-bold px-2 py-0.5 rounded-md bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                                                        ✓ Done
                                                    </span>
                                                )}
                                            </div>

                                            {/* Activity Title */}
                                            <p className={cn(
                                                'text-sm font-semibold text-neutral-100 leading-snug',
                                                isChecked && 'line-through text-neutral-400'
                                            )}>
                                                {act.activity}
                                            </p>

                                            {/* Location Tag */}
                                            <div className="flex items-center gap-1.5 text-xs text-neutral-400">
                                                <MapPin size={12} className="text-[#FF6B6B] flex-shrink-0" />
                                                <span className="truncate">{act.location}</span>
                                            </div>

                                            {/* Insider Tip Callout */}
                                            {act.tip && (
                                                <div className="flex items-start gap-2 text-xs text-purple-200 bg-purple-950/50 border border-purple-500/30 rounded-xl p-3 mt-2">
                                                    <Lightbulb size={13} className="flex-shrink-0 mt-0.5 text-amber-400" />
                                                    <div className="leading-relaxed">
                                                        <span className="text-[10px] font-bold uppercase tracking-wider text-amber-300 block mb-0.5">
                                                            Insider Note
                                                        </span>
                                                        <span className="text-neutral-200">{act.tip}</span>
                                                    </div>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </motion.div>
    );
}

